# Generated by Django 2.1.8 on 2020-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='代号')),
                ('place', models.CharField(max_length=100, verbose_name='出身地')),
                ('health', models.IntegerField(verbose_name='生命上限')),
                ('attack', models.IntegerField(verbose_name='初始攻击')),
                ('defined', models.IntegerField(verbose_name='初始防御')),
                ('magic', models.IntegerField(verbose_name='初始魔抗')),
                ('a_time', models.CharField(max_length=100, verbose_name='再部署时间')),
                ('s_cost', models.IntegerField(verbose_name='初始部署费用')),
                ('blocked', models.IntegerField(verbose_name='初始阻挡')),
                ('between', models.FloatField(verbose_name='初始攻击间隔')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('special', models.CharField(max_length=500, verbose_name='特性')),
            ],
        ),
    ]
