# Generated by Django 2.1.8 on 2020-08-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsql', '0002_zhenghe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='special',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='tag',
        ),
    ]
