# Generated by Django 2.1.8 on 2020-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsql', '0003_auto_20200805_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='between',
            field=models.CharField(max_length=100, verbose_name='初始攻击间隔'),
        ),
    ]
