# Generated by Django 2.1.8 on 2020-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsql', '0004_auto_20200805_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhenghe',
            name='pace',
            field=models.CharField(default='人类', max_length=100, verbose_name='物种'),
            preserve_default=False,
        ),
    ]
